# terraform/keycloak_clients.tf
#
# Phase 7b — OIDC clients for the four apps that get SSO in 7c/7d.
#
# All four are CONFIDENTIAL clients (server-side, not single-page apps).
# Client secrets are auto-generated by Keycloak; we surface them as sensitive
# Terraform outputs so 7c can read them when wiring per-app config.

# ── Nextcloud ───────────────────────────────────────────────────────────────
# user_oidc app handles the auth code → token exchange. Redirect URI shape
# matches Nextcloud 30 + user_oidc 7.x.

resource "keycloak_openid_client" "nextcloud" {
  realm_id  = keycloak_realm.nimbus.id
  client_id = "nextcloud"
  name      = "Nextcloud"
  enabled   = true

  access_type                  = "CONFIDENTIAL"
  standard_flow_enabled        = true
  direct_access_grants_enabled = false
  service_accounts_enabled     = false

  valid_redirect_uris = [
    "https://${var.nextcloud_domain}/apps/user_oidc/code",
    "https://cloud.nimbus.local/apps/user_oidc/code",
    "https://cloud-app.nimbus.local/apps/user_oidc/code",
  ]

  web_origins = [
    "https://${var.nextcloud_domain}",
    "https://cloud.nimbus.local",
    "https://cloud-app.nimbus.local",
  ]

  login_theme = "keycloak"
}

# ── Grafana ─────────────────────────────────────────────────────────────────
# generic_oauth — Grafana validates against /realms/nimbus/protocol/openid-connect.

resource "keycloak_openid_client" "grafana" {
  realm_id  = keycloak_realm.nimbus.id
  client_id = "grafana"
  name      = "Grafana"
  enabled   = true

  access_type                  = "CONFIDENTIAL"
  standard_flow_enabled        = true
  direct_access_grants_enabled = false
  service_accounts_enabled     = false

  valid_redirect_uris = [
    "https://mon.nimbus.local/login/generic_oauth",
  ]

  web_origins = [
    "https://mon.nimbus.local",
  ]

  login_theme = "keycloak"
}

# Group-membership claim — Grafana's role_attribute_path JMESPath expression
# (in modules/monitoring user-data) reads `groups` to map Keycloak groups
# (grafana-admins / grafana-editors) to Grafana roles (Admin / Editor / Viewer).
resource "keycloak_openid_group_membership_protocol_mapper" "grafana_groups" {
  realm_id            = keycloak_realm.nimbus.id
  client_id           = keycloak_openid_client.grafana.id
  name                = "groups"
  claim_name          = "groups"
  full_path           = false
  add_to_id_token     = true
  add_to_access_token = true
  add_to_userinfo     = true
}

# ── MinIO console ───────────────────────────────────────────────────────────
# Console redirects to /oauth_callback. We list both the direct VM URL and
# the eventual nimbus.local hostname (added in Phase 8).

resource "keycloak_openid_client" "minio_console" {
  realm_id  = keycloak_realm.nimbus.id
  client_id = "minio-console"
  name      = "MinIO Console"
  enabled   = true

  access_type                  = "CONFIDENTIAL"
  standard_flow_enabled        = true
  direct_access_grants_enabled = false
  service_accounts_enabled     = false

  valid_redirect_uris = [
    "http://${var.nimbus_s3_ip}:9001/oauth_callback",
    "https://s3.nimbus.local/oauth_callback",
  ]

  web_origins = [
    "http://${var.nimbus_s3_ip}:9001",
    "https://s3.nimbus.local",
  ]

  login_theme = "keycloak"
}

# ── Vault ───────────────────────────────────────────────────────────────────
# Vault's UI hits /ui/vault/auth/oidc/oidc/callback; CLI hits /oidc/callback
# (auth method backend path = "oidc"). Direct to nimbus-vault — no ALB.

resource "keycloak_openid_client" "vault" {
  realm_id  = keycloak_realm.nimbus.id
  client_id = "vault"
  name      = "HashiCorp Vault"
  enabled   = true

  access_type                  = "CONFIDENTIAL"
  standard_flow_enabled        = true
  direct_access_grants_enabled = false
  service_accounts_enabled     = false

  valid_redirect_uris = [
    "https://vault.nimbus.local:8200/ui/vault/auth/oidc/oidc/callback",
    "https://vault.nimbus.local:8200/oidc/callback",
    # Loopback for `vault login -method=oidc` from the operator's machine.
    "http://localhost:8250/oidc/callback",
  ]

  web_origins = [
    "https://vault.nimbus.local:8200",
  ]

  login_theme = "keycloak"
}

# Group claim — the Vault OIDC role's bound_claims reads `groups` to gate
# `vault-admins` Keycloak group → `admin` Vault policy.
resource "keycloak_openid_group_membership_protocol_mapper" "vault_groups" {
  realm_id            = keycloak_realm.nimbus.id
  client_id           = keycloak_openid_client.vault.id
  name                = "groups"
  claim_name          = "groups"
  full_path           = false
  add_to_id_token     = true
  add_to_access_token = true
  add_to_userinfo     = true
}

# ── Outputs ──────────────────────────────────────────────────────────────────
# Client secrets — read these in 7c to plumb each app's OIDC config.

output "keycloak_client_secret_nextcloud" {
  value     = keycloak_openid_client.nextcloud.client_secret
  sensitive = true
}

output "keycloak_client_secret_grafana" {
  value     = keycloak_openid_client.grafana.client_secret
  sensitive = true
}

output "keycloak_client_secret_minio_console" {
  value     = keycloak_openid_client.minio_console.client_secret
  sensitive = true
}

output "keycloak_client_secret_vault" {
  value     = keycloak_openid_client.vault.client_secret
  sensitive = true
}
